spring:
  application:
    name: Ktree

  datasource:
    url: jdbc:postgresql://k3s.club012.com:5432/kpc_backoffice
    username: kpc_backoffice
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml,classpath:mappers/postgres/*.xml

server:
  port: 8080
